# Generated by Django 3.2.15 on 2022-12-14 17:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('reg_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration number')),
                ('ref_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Referral Code')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='user/passport', verbose_name='Display Photo')),
                ('vendor', models.BooleanField(default=False, verbose_name='Vendor?')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('gave_consent', models.BooleanField(default=False, verbose_name="Share my registration data with trustscrow's content providers for marketing purposes. This confirms you are up to the legal age approved in your country.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'ordering': ['-date_joined'],
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Wallet Address')),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet Address',
                'verbose_name_plural': 'User Wallet Addresses',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('p_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('increase', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SavedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_on_card', models.CharField(max_length=255)),
                ('card_no', models.CharField(max_length=18)),
                ('cvv', models.CharField(blank=True, max_length=18, null=True)),
                ('card_exp_month', models.CharField(blank=True, max_length=2)),
                ('card_exp_year', models.CharField(blank=True, max_length=4)),
                ('card_provider', models.CharField(default='master', max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Card',
                'verbose_name_plural': 'User Saved Cards',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Customer Contact')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Customer Address')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_tagline', models.CharField(blank=True, max_length=255, verbose_name='Company Tagline')),
                ('company_reg_no', models.CharField(blank=True, max_length=255, verbose_name='Company RC Number')),
                ('company_rep', models.CharField(blank=True, max_length=255, verbose_name='Company Representative')),
                ('company_website', models.URLField(blank=True, verbose_name='Company Website')),
                ('company_phone_I', models.CharField(blank=True, max_length=16, verbose_name='Company Contact I')),
                ('company_phone_II', models.CharField(blank=True, max_length=16, verbose_name='Company Contact II')),
                ('company_address', models.CharField(blank=True, max_length=500, verbose_name='Company Address')),
                ('company_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country', verbose_name='Company Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('acc_no', models.CharField(max_length=17)),
                ('acc_name', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=11)),
                ('verified', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_account', to='currency.banks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Bank',
                'verbose_name_plural': 'User Saved Banks',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
