# Generated by Django 4.0.8 on 2023-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
