# Generated by Django 4.0.8 on 2023-01-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Temporary Password'),
        ),
    ]
