# Generated by Django 4.0.8 on 2023-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
