# Generated by Django 3.2.15 on 2022-12-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
        ('escrow', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_item', to='workshop.products'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_order', to='escrow.contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.productlocalization'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
