# Generated by Django 3.2.15 on 2022-12-14 17:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contract_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique ID')),
                ('creator', models.CharField(choices=[('Contractor', 'Contractor'), ('Vendor', 'Vendor')], default='Vendor', max_length=255, verbose_name='Contract Creator')),
                ('contract_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT')], default='PRODUCT', max_length=255, verbose_name='Contract Type')),
                ('slug', models.SlugField(blank=True, max_length=500, verbose_name='Slug')),
                ('terms_agreement', tinymce.models.HTMLField()),
                ('terms_for_termination', tinymce.models.HTMLField()),
                ('vendor', models.CharField(blank=True, max_length=500, null=True, verbose_name="Vendor's Name")),
                ('vendor_phone', models.CharField(blank=True, max_length=500, null=True, verbose_name="Vendor's Phone Number")),
                ('vendor_email', models.EmailField(blank=True, max_length=254, verbose_name="Vendor's Email")),
                ('vendor_address', models.CharField(blank=True, max_length=500, null=True, verbose_name="Vendor's Address")),
                ('buyer', models.CharField(blank=True, max_length=500, null=True, verbose_name="Buyer's Name")),
                ('buyer_phone', models.CharField(blank=True, max_length=500, null=True, verbose_name="Buyer's Phone Number")),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name="Buyer's Email")),
                ('buyer_address', models.CharField(blank=True, max_length=500, null=True, verbose_name="Buyer's Address")),
                ('vendor_approve', models.BooleanField(default=False)),
                ('buyer_approve', models.BooleanField(default=False)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Contract Price')),
                ('contract_paid', models.BooleanField(default=False)),
                ('contract_termination', models.DateField(blank=True, null=True, verbose_name='Contract Termination Date')),
                ('contract_started', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_ended', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dispute_detail', tinymce.models.HTMLField()),
                ('dispute_resolve', tinymce.models.HTMLField()),
                ('dispute_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contract Dispute',
                'verbose_name_plural': 'Contract Disputes',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisputeMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Contract Dispute Message',
                'verbose_name_plural': 'Contract Dispute Messages',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('detail', tinymce.models.HTMLField()),
                ('deadline', models.DateField()),
                ('accepted', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['deadline'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT')], default='PRODUCT', max_length=255, verbose_name='Transaction Type')),
                ('transaction_status', models.CharField(choices=[('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=255, verbose_name='Transaction Status')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tx_code', models.CharField(blank=True, max_length=500, verbose_name='Transaction Ref')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
