# Generated by Django 3.2.15 on 2022-12-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transaction', to='escrow.contract'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestones',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_milestone', to='escrow.contract'),
        ),
        migrations.AddField(
            model_name='disputemessages',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_message', to='escrow.dispute'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='escrow.contract'),
        ),
    ]
