# Generated by Django 4.0.8 on 2023-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_rename_tx_code_transactions_ref_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contract Title'),
        ),
    ]
