# Generated by Django 4.0.8 on 2023-01-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_contract_contract_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
