# Generated by Django 4.0.8 on 2023-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_contract_payment_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='tf_code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Transfer Code'),
        ),
    ]
