# Generated by Django 4.0.8 on 2023-01-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_transactions_tf_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_sent',
            field=models.BooleanField(default=False),
        ),
    ]
