# Generated by Django 3.2.15 on 2022-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productlocalization',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=4500.0, max_digits=20, verbose_name='Cost to deliver'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_type',
            field=models.CharField(default='PRODUCT', max_length=20, verbose_name='Product Type'),
        ),
    ]
